spring.application.name=WeatherFitBackend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#spring.datasource.url=jdbc:mysql://localhost:3306/weatherfit
#spring.datasource.username=root
#spring.datasource.password=yourpassword
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update

weather.api.url=http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
weather.api.key=lHaFar6IrrcZnH7t8Qf9FDM16SOAWCnPBn4pcg1%2ByGOe9D%2Fiizyse8XT0vPDu2Y1ppqWUUSbb5lX29dH1AtWhg%3D%3D
