spring.application.name=WeatherFitBackend
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#spring.datasource.url=jdbc:mysql://localhost:3306/weatherfit
#spring.datasource.username=root
#spring.datasource.password=yourpassword
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update

weather.api.url=http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0
weather.api.key=w6nrvy1kuve4ZFuIxZf3k3xN%2F24B3LcjgwZYTT5GpRhXDqXVFYqEiVHIvm%2BKXS2cg%2BmL1zcLezpAT13YgESvsw%3D%3D
