INSERT INTO clothes (category, name, gender, image_url, min_temperature, max_temperature) VALUES
                                                                                              ('아우터', '롱패딩_블랙', 'UNISEX', 'https://example.com/롱패딩(공용1).jpg', -50, 0),
                                                                                              ('아우터', '하입 덕 다운 패딩_블랙', 'MALE', 'https://example.com/숏패딩(남1).jpg', -50, 10),
                                                                                              ('아우터', '크로스 라인 패딩_웜 그레이', 'MALE', 'https://example.com/숏패딩(남2).jpg', -50, 10),
                                                                                              ('아우터', '눕시 패딩_블랙', 'MALE', 'https://example.com/숏패딩(남3).jpg', -50, 10),
                                                                                              ('아우터', '웰론 글로시 패딩_블랙', 'FEMALE', 'https://example.com/숏패딩(여1).jpg', -50, 10),
                                                                                              ('아우터', '눕시 패딩_크림', 'FEMALE', 'https://example.com/숏패딩(여2).jpg', -50, 10),
                                                                                              ('아우터', '레더 크롭 조끼패딩_블랙', 'FEMALE', 'https://example.com/조끼패딩(여1).jpg', 0, 10),
                                                                                              ('아우터', '3버튼 체스터필드 싱글 코트_블랙', 'MALE', 'https://example.com/겨울코트(남1).jpg', 0, 10),
                                                                                              ('아우터', '멜톤 울 코트_브라운', 'MALE', 'https://example.com/겨울코트(남2).jpg', 0, 10),
                                                                                              ('아우터', '더블 울 하프 코트_차콜', 'FEMALE', 'https://example.com/겨울코트(여1).jpg', 0, 10),
                                                                                              ('아우터', '벨티드 울 코트_블랙', 'FEMALE', 'https://example.com/겨울코트(여2).jpg', 0, 10),
                                                                                              ('아우터', '후드 양털 떡볶이 숏코트_베이지', 'FEMALE', 'https://example.com/겨울코트(여3).jpg', 0, 10),
                                                                                              ('아우터', '오버사이즈 리얼 무스탕_블랙', 'MALE', 'https://example.com/무스탕(남1).jpg', 0, 10),
                                                                                              ('아우터', '크랙 시어링 무스탕_브라운', 'MALE', 'https://example.com/무스탕(남2).jpg', 0, 10),
                                                                                              ('아우터', '오버핏 시어링 무스탕_브라운', 'FEMALE', 'https://example.com/무스탕(여1).jpg', 0, 10),
                                                                                              ('아우터', '스웨이드 무스탕_베이지', 'FEMALE', 'https://example.com/무스탕(여2).jpg', 0, 10),
                                                                                              ('아우터', '니트 후드 더플 코트_브라운', 'MALE', 'https://example.com/가을코트(남1).jpg', 10, 15),
                                                                                              ('아우터', '오버핏 트렌치 롱코트_브라운', 'MALE', 'https://example.com/가을코트(남2).jpg', 10, 15),
                                                                                              ('아우터', '오버핏 트렌치 코트_아이보리', 'FEMALE', 'https://example.com/가을코트(여1).jpg', 10, 15),
                                                                                              ('아우터', '하프 트렌치 숏코트_베이지', 'FEMALE', 'https://example.com/가을코트(여2).jpg', 10, 15),
                                                                                              ('아우터', '양 가죽 자켓_다크브라운', 'MALE', 'https://example.com/가죽자켓(남1).jpg', 10, 15),
                                                                                              ('아우터', '가죽 자켓_블랙', 'MALE', 'https://example.com/가죽자켓(남2).jpg', 10, 15),
                                                                                              ('아우터', '가죽 자켓_다크브라운', 'FEMALE', 'https://example.com/가죽자켓(여1).jpg', 10, 15),
                                                                                              ('아우터', '밴딩 크롭 레더 자켓_브라운', 'FEMALE', 'https://example.com/가죽자켓(여2).jpg', 10, 15),
                                                                                              ('아우터', '스탠다드 플리스 집업 자켓_블랙', 'UNISEX', 'https://example.com/후리스(공용1).jpg', 10, 15),
                                                                                              ('아우터', '스탠다드 플리스 집업 자켓_아이보리', 'UNISEX', 'https://example.com/후리스(공용2).jpg', 10, 15),
                                                                                              ('아우터', '스웨이드 지퍼 블루종 자켓_올리브브라운', 'MALE', 'https://example.com/블루종(남1).jpg', 10, 20),
                                                                                              ('아우터', '미니멀 코튼 블루종 자켓_베이지', 'MALE', 'https://example.com/블루종(남2).jpg', 10, 20),
                                                                                              ('아우터', '블루종 스웨이드 자켓_블랙', 'MALE', 'https://example.com/블루종(남3).jpg', 10, 20),
                                                                                              ('아우터', '세미크롭 밴딩집업_브라운', 'FEMALE', 'https://example.com/블루종(여1).jpg', 10, 20),
                                                                                              ('아우터', '레더 블루종 자켓_블랙', 'FEMALE', 'https://example.com/블루종(여2).jpg', 10, 20),
                                                                                              ('아우터', '빈티지 워싱 코튼 크롭 자켓_와인', 'FEMALE', 'https://example.com/블루종(여3).jpg', 10, 20),
                                                                                              ('아우터', '셔링 데님 자켓_미드블루', 'MALE', 'https://example.com/데님자켓(남1).jpg', 10, 20),
                                                                                              ('아우터', '트러커 데님 자켓_인디고', 'MALE', 'https://example.com/데님자켓(남2).jpg', 10, 20),
                                                                                              ('아우터', '빈티지 데님 자켓_더스티블루', 'FEMALE', 'https://example.com/데님자켓(여1).jpg', 10, 20),
                                                                                              ('아우터', '빈티지 워싱 데님 자켓_블루', 'FEMALE', 'https://example.com/데님자켓(여2).jpg', 10, 20),
                                                                                              ('아우터', '레트로 체크 자켓_베이지', 'MALE', 'https://example.com/블레이저(남1).jpg', 10, 20),
                                                                                              ('아우터', '원버튼 블레이저 자켓_블랙', 'MALE', 'https://example.com/블레이저(남2).jpg', 10, 20),
                                                                                              ('아우터', '루즈핏 싱글 미디 자켓_베이지', 'FEMALE', 'https://example.com/블레이저(여1).jpg', 10, 20),
                                                                                              ('아우터', '세미오버핏 싱글 블레이저 자켓_블랙', 'FEMALE', 'https://example.com/블레이저(여2).jpg', 10, 20),
                                                                                              ('아우터', '크로매틱 워셔블 가디건_그레이', 'MALE', 'https://example.com/가디건(남1).jpg', 10, 20),
                                                                                              ('아우터', '레인 드롭 니트 가디건_블랙', 'MALE', 'https://example.com/가디건(남2).jpg', 10, 20),
                                                                                              ('아우터', '레이어드 가디건_그레이', 'FEMALE', 'https://example.com/가디건(여1).jpg', 10, 20),
                                                                                              ('아우터', '리본 페이트 니트가디건_그린', 'FEMALE', 'https://example.com/가디건(여2).jpg', 10, 20),
                                                                                              ('아우터', '풀 집업 가디건_아이보리', 'FEMALE', 'https://example.com/가디건(여3).jpg', 10, 20),
                                                                                              ('아우터', '심볼 사이드 트랙자켓_브라운', 'MALE', 'https://example.com/집업(남1).jpg', 10, 20),
                                                                                              ('아우터', '투웨이 스웻 후드 집업_그레이', 'MALE', 'https://example.com/후드집업(남1).jpg', 10, 20),
                                                                                              ('아우터', '웨이트 니트 후드 집업_베이지', 'MALE', 'https://example.com/후드집업(남2).jpg', 10, 20),
                                                                                              ('아우터', '스트라이프 단가라 울 후드 집업_브라운', 'FEMALE', 'https://example.com/후드집업(여1).jpg', 10, 20),
                                                                                              ('아우터', '페인팅 오버핏 후드 집업_메란지그레이', 'FEMALE', 'https://example.com/후드집업(여2).jpg', 10, 20),
                                                                                              ('아우터', '하이드후드 트랙 자켓_블랙', 'MALE', 'https://example.com/바람막이(남1).jpg', 10, 20),
                                                                                              ('아우터', '타슬란 윈드 테이커 자켓_라이트그레이', 'MALE', 'https://example.com/바람막이(남2).jpg', 10, 20),
                                                                                              ('아우터', '우븐 윈드브레이커_화이트', 'FEMALE', 'https://example.com/바람막이(여1).jpg', 10, 20),
                                                                                              ('아우터', '오버핏 윈드브레이커 자켓_블랙', 'FEMALE', 'https://example.com/바람막이(여2).jpg', 10, 20),
                                                                                              ('상의', '스프라이트 모헤어 니트_네이비', 'MALE', 'https://example.com/니트/스웨터(남1).jpg', -50, 15),
                                                                                              ('상의', '브이넥 케이블 니트_베이지', 'MALE', 'https://example.com/니트/스웨터(남2).jpg', -50, 15),
                                                                                              ('상의', '빈티지 라운드 니트티_화이트', 'MALE', 'https://example.com/니트/스웨터(남3).jpg', -50, 15),
                                                                                              ('상의', '니티드 스웨트 셔츠_원더화이트', 'FEMALE', 'https://example.com/니트/스웨터(여1).jpg', -50, 15),
                                                                                              ('상의', '메쉬 루즈핏 니트_화이트', 'FEMALE', 'https://example.com/니트/스웨터(여2).jpg', -50, 15),
                                                                                              ('상의', '브이넥 맨투맨_블랙', 'FEMALE', 'https://example.com/니트/스웨터(여3).jpg', -50, 15),
                                                                                              ('상의', '라프라 맨투맨_카키', 'MALE', 'https://example.com/맨투맨(남1).jpg', -50, 15),
                                                                                              ('상의', '레글런 스웨트셔츠_블랙', 'MALE', 'https://example.com/맨투맨(남2).jpg', -50, 15),
                                                                                              ('상의', '스웨트 맨투맨_그레이', 'MALE', 'https://example.com/맨투맨(남3).jpg', -50, 15),
                                                                                              ('상의', '나그랑 오버핏 맨투맨_와인', 'FEMALE', 'https://example.com/맨투맨(여1).jpg', -50, 15),
                                                                                              ('상의', '후리스 맨투맨_크림', 'FEMALE', 'https://example.com/맨투맨(여2).jpg', -50, 15),
                                                                                              ('상의', '루즈핏 맨투맨_그레이', 'FEMALE', 'https://example.com/맨투맨(여3).jpg', -50, 15),
                                                                                              ('상의', '무지 후드 티셔츠_블랙', 'MALE', 'https://example.com/후드 티셔츠(남1).jpg', -50, 15),
                                                                                              ('상의', '로고 후드 티셔츠_그레이', 'MALE', 'https://example.com/후드 티셔츠(남2).jpg', -50, 15),
                                                                                              ('상의', '셔링 후드 티셔츠_그레이', 'FEMALE', 'https://example.com/후드 티셔츠(여1).jpg', -50, 15),
                                                                                              ('상의', '아방핏 후드 티셔츠_네이비', 'FEMALE', 'https://example.com/후드 티셔츠(여2).jpg', -50, 15),
                                                                                              ('상의', '체크 셔츠_그레이', 'UNISEX', 'https://example.com/셔츠/블라우스(공용1).jpg', 15, 50),
                                                                                              ('상의', '루즈핏 린넨 오픈 카라 셔츠_화이트', 'MALE', 'https://example.com/셔츠/블라우스(남1).jpg', 15, 50),
                                                                                              ('상의', '루즈핏 린넨 오픈 카라 셔츠_블랙', 'MALE', 'https://example.com/셔츠/블라우스(남2).jpg', 15, 50),
                                                                                              ('상의', '오버핏 옥스포드 셔츠_화이트', 'MALE', 'https://example.com/셔츠/블라우스(남3).jpg', 15, 50),
                                                                                              ('상의', '오버핏 옥스포드 셔츠_라이트 블루', 'MALE', 'https://example.com/셔츠/블라우스(남4).jpg', 15, 50),
                                                                                              ('상의', '워크 셔츠_카키', 'MALE', 'https://example.com/셔츠/블라우스(남5).jpg', 15, 50),
                                                                                              ('상의', '스프라이프 셔츠_스카이블루', 'MALE', 'https://example.com/셔츠/블라우스(남6).jpg', 15, 50),
                                                                                              ('상의', '오프 셔츠_화이트', 'FEMALE', 'https://example.com/셔츠/블라우스(여1).jpg', 15, 50),
                                                                                              ('상의', '프릴 레이스 블라우스_화이트', 'FEMALE', 'https://example.com/셔츠/블라우스(여2).jpg', 15, 50),
                                                                                              ('상의', '스트라이프 셔츠_핑크', 'FEMALE', 'https://example.com/셔츠/블라우스(여3).jpg', 15, 50),
                                                                                              ('상의', '클래식 롱 슬리브_화이트', 'MALE', 'https://example.com/긴소매 티셔츠(남1).jpg', 15, 50),
                                                                                              ('상의', '스트라이프 롱 슬리브_블랙', 'MALE', 'https://example.com/긴소매 티셔츠(남2).jpg', 15, 50),
                                                                                              ('상의', '언발 나시 티셔츠_카키', 'FEMALE', 'https://example.com/긴소매 티셔츠(여1).jpg', 15, 50),
                                                                                              ('상의', '레이어드 티셔츠_그레이', 'FEMALE', 'https://example.com/긴소매 티셔츠(여2).jpg', 15, 50),
                                                                                              ('상의', '골지 버튼 라운드 티셔츠_네이비', 'FEMALE', 'https://example.com/긴소매 티셔츠(여3).jpg', 15, 50),
                                                                                              ('상의', '스프라이트 카라 티셔츠_차콜그레이', 'MALE', 'https://example.com/피케/카라 티셔츠(남1).jpg', 15, 50),
                                                                                              ('상의', '럭비 카라 셔츠_다크그레이', 'MALE', 'https://example.com/피케/카라 티셔츠(남2).jpg', 15, 50),
                                                                                              ('상의', '스트라이프 카라 오버핏 티셔츠_크림', 'FEMALE', 'https://example.com/피케/카라 티셔츠(여1).jpg', 15, 50),
                                                                                              ('상의', '반집업 카라 티셔츠_그레이', 'FEMALE', 'https://example.com/피케/카라 티셔츠(여2).jpg', 15, 50),
                                                                                              ('상의', 'M로고 반팔_다크그레이', 'MALE', 'https://example.com/반소매 티셔츠(남1).jpg', 20, 50),
                                                                                              ('상의', 'M로고 반팔_블랙', 'MALE', 'https://example.com/반소매 티셔츠(남2).jpg', 20, 50),
                                                                                              ('상의', 'M로고 반팔_화이트', 'MALE', 'https://example.com/반소매 티셔츠(남3).jpg', 20, 50),
                                                                                              ('상의', 'M로고 반팔_그레이', 'MALE', 'https://example.com/반소매 티셔츠(남4).jpg', 20, 50),
                                                                                              ('상의', 'M로고 반팔_딥레드', 'MALE', 'https://example.com/반소매 티셔츠(남5).jpg', 20, 50),
                                                                                              ('상의', 'M무지 반팔_화이트', 'MALE', 'https://example.com/반소매 티셔츠(남6).jpg', 20, 50),
                                                                                              ('상의', 'M무지 반팔_블랙', 'MALE', 'https://example.com/반소매 티셔츠(남7).jpg', 20, 50),
                                                                                              ('상의', '리본 꽃자수 퍼프 소매_아이보리', 'FEMALE', 'https://example.com/반소매 티셔츠(여1).jpg', 20, 50),
                                                                                              ('상의', 'U넥 스트랩 반팔_블랙', 'FEMALE', 'https://example.com/반소매 티셔츠(여2).jpg', 20, 50),
                                                                                              ('상의', 'W로고 반팔_차콜', 'FEMALE', 'https://example.com/반소매 티셔츠(여3).jpg', 20, 50),
                                                                                              ('상의', 'W로고 반팔_화이트', 'FEMALE', 'https://example.com/반소매 티셔츠(여4).jpg', 20, 50),
                                                                                              ('상의', 'W로고 반팔_네이비', 'FEMALE', 'https://example.com/반소매 티셔츠(여5).jpg', 20, 50),
                                                                                              ('상의', '크롭 반팔_차콜', 'FEMALE', 'https://example.com/반소매 티셔츠(여6).jpg', 20, 50),
                                                                                              ('상의', '투포켓 데님 하프 셔츠_블랙', 'MALE', 'https://example.com/반팔 셔츠(남1).jpg', 20, 50),
                                                                                              ('상의', '웨스턴 데님 하프 셔츠_더스트 인디고', 'MALE', 'https://example.com/반팔 셔츠(남2).jpg', 20, 50),
                                                                                              ('상의', '체크 하프 셔츠_블랙', 'MALE', 'https://example.com/반팔 셔츠(남3).jpg', 20, 50),
                                                                                              ('상의', '핀턱 V넥 하프 블라우스_화이트', 'FEMALE', 'https://example.com/반팔 셔츠(여1).jpg', 20, 50),
                                                                                              ('상의', '버튼 카라 하프 블라우스_블랙', 'FEMALE', 'https://example.com/반팔 셔츠(여2).jpg', 20, 50),
                                                                                              ('상의', '버튼 포인트 하프 블라우스_민트', 'FEMALE', 'https://example.com/반팔 셔츠(여3).jpg', 20, 50),
                                                                                              ('상의', '반소매 카라 하프 셔츠_화이트', 'MALE', 'https://example.com/피케/카라 하프 티셔츠(남2).jpg', 20, 50),
                                                                                              ('상의', '반소매 카라 하프 셔츠_블랙', 'MALE', 'https://example.com/피케/카라 하프 티셔츠(남1).jpg', 20, 50),
                                                                                              ('상의', '카라 아노락 하프 티셔츠_네이비', 'FEMALE', 'https://example.com/피케/카라 하프 티셔츠(여1).jpg', 20, 50),
                                                                                              ('상의', '오버핏 반집업 반팔티셔츠_아이보리', 'FEMALE', 'https://example.com/피케/카라 하프 티셔츠(여2).jpg', 20, 50),
                                                                                              ('원피스', '퍼프 소매 미니 원피스_화이트', 'FEMALE', 'https://example.com/원피스(여1).jpg', 15, 50),
                                                                                              ('원피스', '레이어드 리본 나시 원피스_카키', 'FEMALE', 'https://example.com/원피스(여2).jpg', 15, 50),
                                                                                              ('원피스', '더블 스트링 미니 원피스_차콜 ', 'FEMALE', 'https://example.com/원피스(여3).jpg', 15, 50),
                                                                                              ('하의', '카고 벌룬 팬츠_카키', 'MALE', 'https://example.com/카고 팬츠(남1).jpg', -50, 50),
                                                                                              ('하의', '스트링 카고 와이드 팬츠_베이지', 'MALE', 'https://example.com/카고 팬츠(남2).jpg', -50, 50),
                                                                                              ('하의', '투버클 카고 팬츠_차콜', 'FEMALE', 'https://example.com/카고 팬츠(여1).jpg', -50, 50),
                                                                                              ('하의', '투버클 카고 와이드 팬츠_베이지', 'FEMALE', 'https://example.com/카고 팬츠(여2).jpg', -50, 50),
                                                                                              ('하의', '와이드 데님 팬츠_흑청', 'MALE', 'https://example.com/데님 팬츠(남1).jpg', -50, 50),
                                                                                              ('하의', '그린페이드 워싱 데님 팬츠_블랙', 'MALE', 'https://example.com/데님 팬츠(남2).jpg', -50, 50),
                                                                                              ('하의', '와이드 데님 팬츠_연청', 'MALE', 'https://example.com/데님 팬츠(남3).jpg', -50, 50),
                                                                                              ('하의', '카펜더 데님 팬츠_연청', 'MALE', 'https://example.com/데님 팬츠(남4).jpg', -50, 50),
                                                                                              ('하의', '워싱 부츠컷 팬츠_흑청', 'FEMALE', 'https://example.com/데님 팬츠(여1).jpg', -50, 50),
                                                                                              ('하의', '워싱 사이드 핀턱 와이트 팬츠_연청', 'FEMALE', 'https://example.com/데님 팬츠(여2).jpg', -50, 50),
                                                                                              ('하의', '세미와이드 워싱 데님 팬츠_연청', 'FEMALE', 'https://example.com/데님 팬츠(여3).jpg', -50, 50),
                                                                                              ('하의', '세미와이드 워싱 데님 팬츠_진청', 'FEMALE', 'https://example.com/데님 팬츠(여4).jpg', -50, 50),
                                                                                              ('하의', '트랙 프론트 포켓 팬츠_블랙', 'MALE', 'https://example.com/트레이닝/조거 팬츠(남1).jpg', -50, 50),
                                                                                              ('하의', '원턱 와이드 스웨트 벌룬 팬츠_그레이', 'MALE', 'https://example.com/트레이닝/조거 팬츠(남2).jpg', -50, 50),
                                                                                              ('하의', '특양면 조거 팬츠_블랙', 'MALE', 'https://example.com/트레이닝/조거 팬츠(남3).jpg', -50, 50),
                                                                                              ('하의', '큐빅 투웨이 와이드 트레이닝 팬츠_블랙', 'FEMALE', 'https://example.com/트레이닝/조거 팬츠(여1).jpg', -50, 50),
                                                                                              ('하의', '슬립핏 부츠컷 트레이닝 팬츠_그레이', 'FEMALE', 'https://example.com/트레이닝/조거 팬츠(여2).jpg', -50, 50),
                                                                                              ('하의', '로 엣지 컨벡스 조거 팬츠_라이트카모', 'FEMALE', 'https://example.com/트레이닝/조거 팬츠(여3).jpg', -50, 50),
                                                                                              ('하의', '세미 와이드 코튼 치노 팬츠_아이보리', 'MALE', 'https://example.com/코튼 팬츠(남1).jpg', -50, 50),
                                                                                              ('하의', '세미 와이드 코튼 치노 팬츠_베이지', 'MALE', 'https://example.com/코튼 팬츠(남2).jpg', -50, 50),
                                                                                              ('하의', '와이드 코튼 핀턱 팬츠_화이트', 'FEMALE', 'https://example.com/코튼 팬츠(여1).jpg', -50, 50),
                                                                                              ('하의', '와이드 코튼 핀턱 팬츠_브라운', 'FEMALE', 'https://example.com/코튼 팬츠(여2).jpg', -50, 50),
                                                                                              ('하의', '와이드 슬랙스_블랙', 'MALE', 'https://example.com/슬랙스(남1).jpg', -50, 50),
                                                                                              ('하의', '스탠다드 슬랙스_올리브그린', 'MALE', 'https://example.com/슬랙스(남2).jpg', -50, 50),
                                                                                              ('하의', '부츠컷 슬랙스_블랙', 'FEMALE', 'https://example.com/슬랙스(여1).jpg', -50, 50),
                                                                                              ('하의', '와이드 슬랙스_아이보리', 'FEMALE', 'https://example.com/슬랙스(여2).jpg', -50, 50),
                                                                                              ('하의', '미디 스커트_차콜', 'FEMALE', 'https://example.com/치마(여1).jpg', 15, 50),
                                                                                              ('하의', '체크 미디 스커트_차콜', 'FEMALE', 'https://example.com/치마(여2).jpg', 15, 50),
                                                                                              ('하의', '벌룬 미니 스커트_블랙', 'FEMALE', 'https://example.com/치마(여3).jpg', 15, 50),
                                                                                              ('하의', '벌룬 미니 스커트_화이트', 'FEMALE', 'https://example.com/치마(여4).jpg', 15, 50),
                                                                                              ('하의', '포켓 미디 스커트_화이트', 'FEMALE', 'https://example.com/치마(여5).jpg', 15, 50),
                                                                                              ('하의', '미디 워싱 데님 스커트_블랙', 'FEMALE', 'https://example.com/치마(여6).jpg', 15, 50),
                                                                                              ('하의', '하이웨스트 린넨 롱 스커트_화이트', 'FEMALE', 'https://example.com/치마(여7).jpg', 15, 50),
                                                                                              ('하의', '애쉬 스케일 데님 버뮤다 팬츠_블랙', 'MALE', 'https://example.com/숏 팬츠(남1).jpg', 20, 50),
                                                                                              ('하의', '스웨이브 버뮤다 팬츠_그레이', 'MALE', 'https://example.com/숏 팬츠(남2).jpg', 20, 50),
                                                                                              ('하의', '프리무드 버뮤다 팬츠_블랙', 'MALE', 'https://example.com/숏 팬츠(남3).jpg', 20, 50),
                                                                                              ('하의', '사이드 스위프 데님 버뮤다 팬츠_연청', 'MALE', 'https://example.com/숏 팬츠(남4).jpg', 20, 50),
                                                                                              ('하의', '버뮤다 핀턱 와이드 트레이닝 팬츠_그레이', 'FEMALE', 'https://example.com/숏 팬츠(여1).jpg', 20, 50),
                                                                                              ('하의', '핀턱 워싱 버뮤다 벌룬 데님 팬츠_중청', 'FEMALE', 'https://example.com/숏 팬츠(여2).jpg', 20, 50),
                                                                                              ('하의', '하이웨스트 데님 숏팬츠_연청', 'FEMALE', 'https://example.com/숏 팬츠(여3).jpg', 20, 50),
                                                                                              ('하의', '하이웨스트 데님 숏팬츠_블랙', 'FEMALE', 'https://example.com/숏 팬츠(여4).jpg', 20, 50),