INSERT INTO clothes (category, name, gender, image_url, min_temperature, max_temperature) VALUES
('아우터', '롱패딩(남1)', 'MALE', 'https://example.com/롱패딩(남1).jpg', -50, 0),
('아우터', '롱패딩(남2)', 'MALE', 'https://example.com/롱패딩(남2).jpg', -50, 0),
('아우터', '롱패딩(여1)', 'FEMALE', 'https://example.com/롱패딩(여1).jpg', -50, 0),
('아우터', '롱패딩(여2)', 'FEMALE', 'https://example.com/롱패딩(여2).jpg', -50, 0),
('아우터', '롱패딩(공용1)', 'UNISEX', 'https://example.com/롱패딩(공용1).jpg', -50, 0),
('아우터', '롱패딩(공용2)', 'UNISEX', 'https://example.com/롱패딩(공용2).jpg', -50, 0),
('아우터', '숏패딩(남1)', 'MALE', 'https://example.com/숏패딩(남1).jpg', -50, 10),
('아우터', '숏패딩(남2)', 'MALE', 'https://example.com/숏패딩(남2).jpg', -50, 10),
('아우터', '숏패딩(여1)', 'FEMALE', 'https://example.com/숏패딩(여1).jpg', -50, 10),
('아우터', '숏패딩(여2)', 'FEMALE', 'https://example.com/숏패딩(여2).jpg', -50, 10),
('아우터', '숏패딩(공용1)', 'UNISEX', 'https://example.com/숏패딩(공용1).jpg', -50, 10),
('아우터', '숏패딩(공용2)', 'UNISEX', 'https://example.com/숏패딩(공용2).jpg', -50, 10),
('아우터', '겨울코트(남1)', 'MALE', 'https://example.com/겨울코트(남1).jpg', 0, 10),
('아우터', '겨울코트(남2)', 'MALE', 'https://example.com/겨울코트(남2).jpg', 0, 10),
('아우터', '겨울코트(여1)', 'FEMALE', 'https://example.com/겨울코트(여1).jpg', 0, 10),
('아우터', '겨울코트(여2)', 'FEMALE', 'https://example.com/겨울코트(여2).jpg', 0, 10),
('아우터', '겨울코트(공용1)', 'UNISEX', 'https://example.com/겨울코트(공용1).jpg', 0, 10),
('아우터', '겨울코트(공용2)', 'UNISEX', 'https://example.com/겨울코트(공용2).jpg', 0, 10),
('아우터', '가을코트(남1)', 'MALE', 'https://example.com/가을코트(남1).jpg', 10, 15),
('아우터', '가을코트(남2)', 'MALE', 'https://example.com/가을코트(남2).jpg', 10, 15),
('아우터', '가을코트(여1)', 'FEMALE', 'https://example.com/가을코트(여1).jpg', 10, 15),
('아우터', '가을코트(여2)', 'FEMALE', 'https://example.com/가을코트(여2).jpg', 10, 15),
('아우터', '가을코트(공용1)', 'UNISEX', 'https://example.com/가을코트(공용1).jpg', 10, 15),
('아우터', '가을코트(공용2)', 'UNISEX', 'https://example.com/가을코트(공용2).jpg', 10, 15),
('아우터', '무스탕(남1)', 'MALE', 'https://example.com/무스탕(남1).jpg', 0, 10),
('아우터', '무스탕(남2)', 'MALE', 'https://example.com/무스탕(남2).jpg', 0, 10),
('아우터', '무스탕(여1)', 'FEMALE', 'https://example.com/무스탕(여1).jpg', 0, 10),
('아우터', '무스탕(여2)', 'FEMALE', 'https://example.com/무스탕(여2).jpg', 0, 10),
('아우터', '무스탕(공용1)', 'UNISEX', 'https://example.com/무스탕(공용1).jpg', 0, 10),
('아우터', '무스탕(공용2)', 'UNISEX', 'https://example.com/무스탕(공용2).jpg', 0, 10),
('아우터', '블루종(남1)', 'MALE', 'https://example.com/블루종(남1).jpg', 10, 20),
('아우터', '블루종(남2)', 'MALE', 'https://example.com/블루종(남2).jpg', 10, 20),
('아우터', '블루종(여1)', 'FEMALE', 'https://example.com/블루종(여1).jpg', 10, 20),
('아우터', '블루종(여2)', 'FEMALE', 'https://example.com/블루종(여2).jpg', 10, 20),
('아우터', '블루종(공용1)', 'UNISEX', 'https://example.com/블루종(공용1).jpg', 10, 20),
('아우터', '블루종(공용2)', 'UNISEX', 'https://example.com/블루종(공용2).jpg', 10, 20),
('아우터', '가죽자켓(남1)', 'MALE', 'https://example.com/가죽자켓(남1).jpg', 10, 20),
('아우터', '가죽자켓(남2)', 'MALE', 'https://example.com/가죽자켓(남2).jpg', 10, 20),
('아우터', '가죽자켓(여1)', 'FEMALE', 'https://example.com/가죽자켓(여1).jpg', 10, 20),
('아우터', '가죽자켓(여2)', 'FEMALE', 'https://example.com/가죽자켓(여2).jpg', 10, 20),
('아우터', '가죽자켓(공용1)', 'UNISEX', 'https://example.com/가죽자켓(공용1).jpg', 10, 20),
('아우터', '가죽자켓(공용2)', 'UNISEX', 'https://example.com/가죽자켓(공용2).jpg', 10, 20),
('아우터', '데님자켓(남1)', 'MALE', 'https://example.com/데님자켓(남1).jpg', 10, 20),
('아우터', '데님자켓(남2)', 'MALE', 'https://example.com/데님자켓(남2).jpg', 10, 20),
('아우터', '데님자켓(여1)', 'FEMALE', 'https://example.com/데님자켓(여1).jpg', 10, 20),
('아우터', '데님자켓(여2)', 'FEMALE', 'https://example.com/데님자켓(여2).jpg', 10, 20),
('아우터', '데님자켓(공용1)', 'UNISEX', 'https://example.com/데님자켓(공용1).jpg', 10, 20),
('아우터', '데님자켓(공용2)', 'UNISEX', 'https://example.com/데님자켓(공용2).jpg', 10, 20),
('아우터', '블레이저(남1)', 'MALE', 'https://example.com/블레이저(남1).jpg', 10, 20),
('아우터', '블레이저(남2)', 'MALE', 'https://example.com/블레이저(남2).jpg', 10, 20),
('아우터', '블레이저(여1)', 'FEMALE', 'https://example.com/블레이저(여1).jpg', 10, 20),
('아우터', '블레이저(여2)', 'FEMALE', 'https://example.com/블레이저(여2).jpg', 10, 20),
('아우터', '블레이저(공용1)', 'UNISEX', 'https://example.com/블레이저(공용1).jpg', 10, 20),
('아우터', '블레이저(공용2)', 'UNISEX', 'https://example.com/블레이저(공용2).jpg', 10, 20),
('아우터', '항공점퍼(남1)', 'MALE', 'https://example.com/항공점퍼(남1).jpg', 10, 20),
('아우터', '항공점퍼(남2)', 'MALE', 'https://example.com/항공점퍼(남2).jpg', 10, 20),
('아우터', '항공점퍼(여1)', 'FEMALE', 'https://example.com/항공점퍼(여1).jpg', 10, 20),
('아우터', '항공점퍼(여2)', 'FEMALE', 'https://example.com/항공점퍼(여2).jpg', 10, 20),
('아우터', '항공점퍼(공용1)', 'UNISEX', 'https://example.com/항공점퍼(공용1).jpg', 10, 20),
('아우터', '항공점퍼(공용2)', 'UNISEX', 'https://example.com/항공점퍼(공용2).jpg', 10, 20),
('아우터', '가디건(남1)', 'MALE', 'https://example.com/가디건(남1).jpg', 10, 20),
('아우터', '가디건(남2)', 'MALE', 'https://example.com/가디건(남2).jpg', 10, 20),
('아우터', '가디건(여1)', 'FEMALE', 'https://example.com/가디건(여1).jpg', 10, 20),
('아우터', '가디건(여2)', 'FEMALE', 'https://example.com/가디건(여2).jpg', 10, 20),
('아우터', '가디건(공용1)', 'UNISEX', 'https://example.com/가디건(공용1).jpg', 10, 20),
('아우터', '가디건(공용2)', 'UNISEX', 'https://example.com/가디건(공용2).jpg', 10, 20),
('아우터', '후드집업(남1)', 'MALE', 'https://example.com/후드집업(남1).jpg', 10, 20),
('아우터', '후드집업(남2)', 'MALE', 'https://example.com/후드집업(남2).jpg', 10, 20),
('아우터', '후드집업(여1)', 'FEMALE', 'https://example.com/후드집업(여1).jpg', 10, 20),
('아우터', '후드집업(여2)', 'FEMALE', 'https://example.com/후드집업(여2).jpg', 10, 20),
('아우터', '후드집업(공용1)', 'UNISEX', 'https://example.com/후드집업(공용1).jpg', 10, 20),
('아우터', '후드집업(공용2)', 'UNISEX', 'https://example.com/후드집업(공용2).jpg', 10, 20),
('아우터', '후리스(남1)', 'MALE', 'https://example.com/후리스(남1).jpg', 10, 20),
('아우터', '후리스(남2)', 'MALE', 'https://example.com/후리스(남2).jpg', 10, 20),
('아우터', '후리스(여1)', 'FEMALE', 'https://example.com/후리스(여1).jpg', 10, 20),
('아우터', '후리스(여2)', 'FEMALE', 'https://example.com/후리스(여2).jpg', 10, 20),
('아우터', '후리스(공용1)', 'UNISEX', 'https://example.com/후리스(공용1).jpg', 10, 20),
('아우터', '후리스(공용2)', 'UNISEX', 'https://example.com/후리스(공용2).jpg', 10, 20),
('상의', '셔츠/블라우스(남1)', 'MALE', 'https://example.com/셔츠/블라우스(남1).jpg', 15, 50),
('상의', '셔츠/블라우스(남2)', 'MALE', 'https://example.com/셔츠/블라우스(남2).jpg', 15, 50),
('상의', '셔츠/블라우스(여1)', 'FEMALE', 'https://example.com/셔츠/블라우스(여1).jpg', 15, 50),
('상의', '셔츠/블라우스(여2)', 'FEMALE', 'https://example.com/셔츠/블라우스(여2).jpg', 15, 50),
('상의', '셔츠/블라우스(공용1)', 'UNISEX', 'https://example.com/셔츠/블라우스(공용1).jpg', 15, 50),
('상의', '셔츠/블라우스(공용2)', 'UNISEX', 'https://example.com/셔츠/블라우스(공용2).jpg', 15, 50),
('상의', '니트/스웨터(남1)', 'MALE', 'https://example.com/니트/스웨터(남1).jpg', -50, 15),
('상의', '니트/스웨터(남2)', 'MALE', 'https://example.com/니트/스웨터(남2).jpg', -50, 15),
('상의', '니트/스웨터(여1)', 'FEMALE', 'https://example.com/니트/스웨터(여1).jpg', -50, 15),
('상의', '니트/스웨터(여2)', 'FEMALE', 'https://example.com/니트/스웨터(여2).jpg', -50, 15),
('상의', '니트/스웨터(공용1)', 'UNISEX', 'https://example.com/니트/스웨터(공용1).jpg', -50, 15),
('상의', '니트/스웨터(공용2)', 'UNISEX', 'https://example.com/니트/스웨터(공용2).jpg', -50, 15),
('상의', '맨투맨(남1)', 'MALE', 'https://example.com/맨투맨(남1).jpg', -50, 15),
('상의', '맨투맨(남2)', 'MALE', 'https://example.com/맨투맨(남2).jpg', -50, 15),
('상의', '맨투맨(여1)', 'FEMALE', 'https://example.com/맨투맨(여1).jpg', -50, 15),
('상의', '맨투맨(여2)', 'FEMALE', 'https://example.com/맨투맨(여2).jpg', -50, 15),
('상의', '맨투맨(공용1)', 'UNISEX', 'https://example.com/맨투맨(공용1).jpg', -50, 15),
('상의', '맨투맨(공용2)', 'UNISEX', 'https://example.com/맨투맨(공용2).jpg', -50, 15),
('상의', '후드 티셔츠(남1)', 'MALE', 'https://example.com/후드 티셔츠(남1).jpg', -50, 15),
('상의', '후드 티셔츠(남2)', 'MALE', 'https://example.com/후드 티셔츠(남2).jpg', -50, 15),
('상의', '후드 티셔츠(여1)', 'FEMALE', 'https://example.com/후드 티셔츠(여1).jpg', -50, 15),
('상의', '후드 티셔츠(여2)', 'FEMALE', 'https://example.com/후드 티셔츠(여2).jpg', -50, 15),
('상의', '후드 티셔츠(공용1)', 'UNISEX', 'https://example.com/후드 티셔츠(공용1).jpg', -50, 15),
('상의', '후드 티셔츠(공용2)', 'UNISEX', 'https://example.com/후드 티셔츠(공용2).jpg', -50, 15),
('상의', '긴소매 티셔츠(남1)', 'MALE', 'https://example.com/긴소매 티셔츠(남1).jpg', 15, 50),
('상의', '긴소매 티셔츠(남2)', 'MALE', 'https://example.com/긴소매 티셔츠(남2).jpg', 15, 50),
('상의', '긴소매 티셔츠(여1)', 'FEMALE', 'https://example.com/긴소매 티셔츠(여1).jpg', 15, 50),
('상의', '긴소매 티셔츠(여2)', 'FEMALE', 'https://example.com/긴소매 티셔츠(여2).jpg', 15, 50),
('상의', '긴소매 티셔츠(공용1)', 'UNISEX', 'https://example.com/긴소매 티셔츠(공용1).jpg', 15, 50),
('상의', '긴소매 티셔츠(공용2)', 'UNISEX', 'https://example.com/긴소매 티셔츠(공용2).jpg', 15, 50),
('상의', '반소매 티셔츠(남1)', 'MALE', 'https://example.com/반소매 티셔츠(남1).jpg', 20, 50),
('상의', '반소매 티셔츠(남2)', 'MALE', 'https://example.com/반소매 티셔츠(남2).jpg', 20, 50),
('상의', '반소매 티셔츠(여1)', 'FEMALE', 'https://example.com/반소매 티셔츠(여1).jpg', 20, 50),
('상의', '반소매 티셔츠(여2)', 'FEMALE', 'https://example.com/반소매 티셔츠(여2).jpg', 20, 50),
('상의', '반소매 티셔츠(공용1)', 'UNISEX', 'https://example.com/반소매 티셔츠(공용1).jpg', 20, 50),
('상의', '반소매 티셔츠(공용2)', 'UNISEX', 'https://example.com/반소매 티셔츠(공용2).jpg', 20, 50),
('상의', '피케/카라 티셔츠(남1)', 'MALE', 'https://example.com/피케/카라 티셔츠(남1).jpg', 20, 50),
('상의', '피케/카라 티셔츠(남2)', 'MALE', 'https://example.com/피케/카라 티셔츠(남2).jpg', 20, 50),
('상의', '피케/카라 티셔츠(여1)', 'FEMALE', 'https://example.com/피케/카라 티셔츠(여1).jpg', 20, 50),
('상의', '피케/카라 티셔츠(여2)', 'FEMALE', 'https://example.com/피케/카라 티셔츠(여2).jpg', 20, 50),
('상의', '피케/카라 티셔츠(공용1)', 'UNISEX', 'https://example.com/피케/카라 티셔츠(공용1).jpg', 20, 50),
('상의', '피케/카라 티셔츠(공용2)', 'UNISEX', 'https://example.com/피케/카라 티셔츠(공용2).jpg', 20, 50),
('상의', '원피스(여1)', 'FEMALE', 'https://example.com/원피스(여1).jpg', 15, 50),
('상의', '원피스(여2)', 'FEMALE', 'https://example.com/원피스(여2).jpg', 15, 50),
('하의', '카고 팬츠(남1)', 'MALE', 'https://example.com/카고 팬츠(남1).jpg', -50, 50),
('하의', '카고 팬츠(남2)', 'MALE', 'https://example.com/카고 팬츠(남2).jpg', -50, 50),
('하의', '카고 팬츠(여1)', 'FEMALE', 'https://example.com/카고 팬츠(여1).jpg', -50, 50),
('하의', '카고 팬츠(여2)', 'FEMALE', 'https://example.com/카고 팬츠(여2).jpg', -50, 50),
('하의', '카고 팬츠(공용1)', 'UNISEX', 'https://example.com/카고 팬츠(공용1).jpg', -50, 50),
('하의', '카고 팬츠(공용2)', 'UNISEX', 'https://example.com/카고 팬츠(공용2).jpg', -50, 50),
('하의', '데님 팬츠(남1)', 'MALE', 'https://example.com/데님 팬츠(남1).jpg', -50, 50),
('하의', '데님 팬츠(남2)', 'MALE', 'https://example.com/데님 팬츠(남2).jpg', -50, 50),
('하의', '데님 팬츠(여1)', 'FEMALE', 'https://example.com/데님 팬츠(여1).jpg', -50, 50),
('하의', '데님 팬츠(여2)', 'FEMALE', 'https://example.com/데님 팬츠(여2).jpg', -50, 50),
('하의', '데님 팬츠(공용1)', 'UNISEX', 'https://example.com/데님 팬츠(공용1).jpg', -50, 50),
('하의', '데님 팬츠(공용2)', 'UNISEX', 'https://example.com/데님 팬츠(공용2).jpg', -50, 50),
('하의', '트레이닝/조거 팬츠(남1)', 'MALE', 'https://example.com/트레이닝/조거 팬츠(남1).jpg', -50, 50),
('하의', '트레이닝/조거 팬츠(남2)', 'MALE', 'https://example.com/트레이닝/조거 팬츠(남2).jpg', -50, 50),
('하의', '트레이닝/조거 팬츠(여1)', 'FEMALE', 'https://example.com/트레이닝/조거 팬츠(여1).jpg', -50, 50),
('하의', '트레이닝/조거 팬츠(여2)', 'FEMALE', 'https://example.com/트레이닝/조거 팬츠(여2).jpg', -50, 50),
('하의', '트레이닝/조거 팬츠(공용1)', 'UNISEX', 'https://example.com/트레이닝/조거 팬츠(공용1).jpg', -50, 50),
('하의', '트레이닝/조거 팬츠(공용2)', 'UNISEX', 'https://example.com/트레이닝/조거 팬츠(공용2).jpg', -50, 50),
('하의', '코튼 팬츠(남1)', 'MALE', 'https://example.com/코튼 팬츠(남1).jpg', -50, 50),
('하의', '코튼 팬츠(남2)', 'MALE', 'https://example.com/코튼 팬츠(남2).jpg', -50, 50),
('하의', '코튼 팬츠(여1)', 'FEMALE', 'https://example.com/코튼 팬츠(여1).jpg', -50, 50),
('하의', '코튼 팬츠(여2)', 'FEMALE', 'https://example.com/코튼 팬츠(여2).jpg', -50, 50),
('하의', '코튼 팬츠(공용1)', 'UNISEX', 'https://example.com/코튼 팬츠(공용1).jpg', -50, 50),
('하의', '코튼 팬츠(공용2)', 'UNISEX', 'https://example.com/코튼 팬츠(공용2).jpg', -50, 50),
('하의', '슬랙스(남1)', 'MALE', 'https://example.com/슬랙스(남1).jpg', -50, 50),
('하의', '슬랙스(남2)', 'MALE', 'https://example.com/슬랙스(남2).jpg', -50, 50),
('하의', '슬랙스(여1)', 'FEMALE', 'https://example.com/슬랙스(여1).jpg', -50, 50),
('하의', '슬랙스(여2)', 'FEMALE', 'https://example.com/슬랙스(여2).jpg', -50, 50),
('하의', '슬랙스(공용1)', 'UNISEX', 'https://example.com/슬랙스(공용1).jpg', -50, 50),
('하의', '슬랙스(공용2)', 'UNISEX', 'https://example.com/슬랙스(공용2).jpg', -50, 50),
('하의', '숏 팬츠(남1)', 'MALE', 'https://example.com/숏 팬츠(남1).jpg', 20, 50),
('하의', '숏 팬츠(남2)', 'MALE', 'https://example.com/숏 팬츠(남2).jpg', 20, 50),
('하의', '숏 팬츠(여1)', 'FEMALE', 'https://example.com/숏 팬츠(여1).jpg', 20, 50),
('하의', '숏 팬츠(여2)', 'FEMALE', 'https://example.com/숏 팬츠(여2).jpg', 20, 50),
('하의', '숏 팬츠(공용1)', 'UNISEX', 'https://example.com/숏 팬츠(공용1).jpg', 20, 50),
('하의', '숏 팬츠(공용2)', 'UNISEX', 'https://example.com/숏 팬츠(공용2).jpg', 20, 50),
('하의', '레깅스(남1)', 'MALE', 'https://example.com/레깅스(남1).jpg', -50, 50),
('하의', '레깅스(남2)', 'MALE', 'https://example.com/레깅스(남2).jpg', -50, 50),
('하의', '레깅스(여1)', 'FEMALE', 'https://example.com/레깅스(여1).jpg', -50, 50),
('하의', '레깅스(여2)', 'FEMALE', 'https://example.com/레깅스(여2).jpg', -50, 50),
('하의', '치마(여1)', 'FEMALE', 'https://example.com/치마(여1).jpg', 15, 50),
('하의', '치마(여2)', 'FEMALE', 'https://example.com/치마(여2).jpg', 15, 50);